#!/usr/bin/python3

import sys
import subprocess

changed_filenames = subprocess.check_output(
        ['git', 'diff-index', '--cached', '--name-only', 'HEAD']).split()
for filename in changed_filenames:
    with open(filename) as f:
        for line_number, line in enumerate(f.readlines(), start=1):
            if 'FIXME' in line:
                print(f"{filename}:{line_number}: {line}\n"
                       "Fix it, wouldn't ya?")
                sys.exit(1)
